// fallback lists, used when /api/categories is unavailable
export interface SelectOption {
  value: string;
  label: string;
}

export const LOCATION_TYPES: SelectOption[] = [
  { value: "istorychne-mistse", label: "Історичне місце" },
  { value: "ozero", label: "Озеро" },
  { value: "richka", label: "Річка" },
  { value: "kempinh", label: "Кемпінг" },
  { value: "kanyon", label: "Каньйон" },
  { value: "zapovidnyk", label: "Заповідник" },
  { value: "termalni-dzherela", label: "Термальні джерела" },
  { value: "lis", label: "Ліс" },
  { value: "natsionalnyi-park", label: "Національний парк" },
  { value: "vodospad", label: "Водоспад" },
  { value: "hory", label: "Гори" },
  { value: "miskyi-vidpochynok", label: "Міський відпочинок" },
  { value: "hirskolyzhnyi-kurort", label: "Гірськолижний курорт" },
  { value: "zamok", label: "Замок" },
  { value: "spa-kurort", label: "Спа-курорт" },
  { value: "pechera", label: "Печера" },
  { value: "more", label: "Море" },
  { value: "plyazh", label: "Пляж" },
];

export const REGIONS: SelectOption[] = [
  { value: "podillya", label: "Поділля" },
  { value: "halychyna", label: "Галичина" },
  { value: "volyn", label: "Волинь" },
  { value: "khmelnychchyna", label: "Хмельниччина" },
  { value: "luhanshchyna", label: "Луганщина" },
  { value: "bukovyna", label: "Буковина" },
  { value: "sumshchyna", label: "Сумщина" },
  { value: "shatski-ozera", label: "Шацькі озера" },
  { value: "kyyivshchyna", label: "Київщина" },
  { value: "vinnychchyna", label: "Вінниччина" },
  { value: "poltavshchyna", label: "Полтавщина" },
  { value: "slobozhanshchyna", label: "Слобожанщина" },
  { value: "zhytomyrshchyna", label: "Житомирщина" },
  { value: "khersonshchyna", label: "Херсонщина" },
  { value: "ukrainski-karpaty", label: "Українські Карпати" },
  { value: "dnistrovskyi-kanyon", label: "Дністровський каньйон" },
  { value: "azovske-uzberezhzhya", label: "Азовське узбережжя" },
  { value: "naddnipryanshchyna", label: "Наддніпрянщина" },
  { value: "ternopilshchyna", label: "Тернопільщина" },
  { value: "kharkivshchyna", label: "Харківщина" },
  { value: "bessarabiya", label: "Бессарабія" },
  { value: "odeshchyna", label: "Одещина" },
  { value: "cherkashchyna", label: "Черкащина" },
  { value: "zaporizhzhya", label: "Запоріжжя" },
  { value: "lvivshchyna", label: "Львівщина" },
  { value: "ivano-frankivshchyna", label: "Івано-Франківщина" },
  { value: "rivnenshchyna", label: "Рівненщина" },
  { value: "dnipropetrovshchyna", label: "Дніпропетровщина" },
  { value: "polissya", label: "Полісся" },
  { value: "chornomorske-uzberezhzhya", label: "Чорноморське узбережжя" },
  { value: "mykolayivshchyna", label: "Миколаївщина" },
  { value: "donechchyna", label: "Донеччина" },
  { value: "zakarpattya", label: "Закарпаття" },
  { value: "hutsulshchyna", label: "Гуцульщина" },
  { value: "chernihivshchyna", label: "Чернігівщина" },
  { value: "kirovohradshchyna", label: "Кіровоградщина" },
];
